### ISSUE TITLE
ClassNotFoundException is thrown when calling SetAgentPassword predefined step

### ISSUE THREAD

**Issue by kovax** [cristal-ise/cristal-ise#137]
```
EXCEPTION:java.lang.ClassNotFoundException: Shiro
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.cristalise.kernel.utils.ObjectProperties.getInstance(ObjectProperties.java:181)
	at org.cristalise.kernel.utils.ObjectProperties.getInstance(ObjectProperties.java:186)
	at org.cristalise.kernel.process.Gateway.getAuthenticator(Gateway.java:356)
	at org.cristalise.kernel.lifecycle.instance.predefined.agent.SetAgentPassword.runActivityLogic(SetAgentPassword.java:69)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:211)
	at org.cristalise.kernel.lifecycle.instance.Workflow.requestAction(Workflow.java:136)
	at org.cristalise.kernel.entity.ItemImplementation.delegatedAction(ItemImplementation.java:251)
	at org.cristalise.kernel.entity.ItemImplementation.requestAction(ItemImplementation.java:225)
	at org.cristalise.kernel.entity.agent.ActiveEntity.requestAction(ActiveEntity.java:119)
```

**Comment by taurus227** [comment]
We encountered another issue, the system logged this error:
```
EXCEPTION:org.apache.shiro.authc.UnknownAccountException: No account found for user [system]
```
@kovax said:

> this error suggests, that the 'system' user is authenticated as it is used as an Admin user to enable password change (edited) 
> but system user does not have any password set, so it does not work with shiro supported authentication, but it was working with the old Authenticator (edited) 
> I could not locate the code which set the system user to the SetAgentPassword predefined step
> normally it is done in a Script associated with an activity

**Comment by taurus227** [comment]
In this line:
https://github.com/cristal-ise/cristal-ise/blob/a197a43afa27ce82c2a26cb2415e0527b6c0369e/kernel/src/main/java/org/cristalise/kernel/scripting/Script.java#L590
the `evaluate()` method invokes the `setActExecEnvironment()` method (if the boolean flag was set), which then properly sets the `agent` input parameter in this line:
https://github.com/cristal-ise/cristal-ise/blob/a197a43afa27ce82c2a26cb2415e0527b6c0369e/kernel/src/main/java/org/cristalise/kernel/scripting/Script.java#L265

But a few lines later, the code in this line:
https://github.com/cristal-ise/cristal-ise/blob/a197a43afa27ce82c2a26cb2415e0527b6c0369e/kernel/src/main/java/org/cristalise/kernel/scripting/Script.java#L605
is:
```
            if (getAllInputParams().containsKey("agent") && getAllInputParams().get("agent") != null) {
                setInputParamValue("agent", Gateway.getProxyManager().getProxy(Gateway.getLookup().getAgentPath("system")));
            }
```
Which means that if this script has an `agent` input parameter definition which is non-null (the value of the parameter definition is `AgentProxy.class`), then we set the script input parameter to the "system" agent! This will override the value that could have been correctly set by the `setActExecEnvironment()` method previously.

**Comment by taurus227** [comment]
Added another check: only set the agent to `system` if no agent has been set yet.

**Comment by taurus227** [comment]
With the above change, if the `item` is set correctly, but then `setInputParamValue()` is invoked with a `null` value and `overwrite` set to `true`, thee correctly set `item` will be overridden with `null`.
![image](https://user-images.githubusercontent.com/5892152/54005409-4e87d200-4194-11e9-925f-9575ce786826.png)
