### ISSUE TITLE
kernel: ProxyManager adds ItemProxy to its cache instead of AgentProxy

### ISSUE THREAD

**Issue by kovax** [cristal-ise/cristal-ise#165]
After creating a new Agent using CreateAgentFromDescription, the ItemProxy cache contains the entry for that Agent but it is an ItemProxy instead of AgentProxy. So if the SetAgentPassword is called, it will be found, but it will fail when the ProxyManager tries to cast it AgentProxy.

**Comment by kovax** [comment]
The case for handling DomainPath is not correct, it can throw this exceptions:

```
EXCEPTION:org.cristalise.kernel.lookup.InvalidItemPathException: Path cannot be null
	at org.cristalise.kernel.lookup.ItemPath.<init>(ItemPath.java:65)
	at org.cristalise.kernel.lookup.DomainPath.setTargetUUID(DomainPath.java:102)
	at org.cristalise.kernel.entity.proxy.ProxyManager.getProxy(ProxyManager.java:260)
	at org.cristalise.kernel.entity.proxy.AgentProxy.getItem(AgentProxy.java:488)
	at org.cristalise.kernel.entity.proxy.AgentProxy.getItem(AgentProxy.java:479)
```
