### ISSUE TITLE
Unable to update collection member upon server restart

### ISSUE THREAD

**Issue by genetorres** [cristal-ise/cristal-ise#173]
Unable to update collection member after restarting the server - Issue related to TitusTech/hmws#386

```
EXCEPTION:java.lang.NullPointerException
	at org.cristalise.kernel.collection.DependencyMember.updateProperties(DependencyMember.java:192)
	at org.cristalise.kernel.collection.Dependency.updateMember(Dependency.java:163)
	at org.cristalise.kernel.lifecycle.instance.predefined.UpdateDependencyMember.runActivityLogic(UpdateDependencyMember.java:80)
	at org.cristalise.kernel.lifecycle.instance.Activity.request(Activity.java:211)
	at org.cristalise.kernel.lifecycle.instance.Workflow.requestAction(Workflow.java:136)
	at org.cristalise.kernel.entity.ItemImplementation.delegatedAction(ItemImplementation.java:251)
	at org.cristalise.kernel.entity.ItemImplementation.requestAction(ItemImplementation.java:225)
	at org.cristalise.kernel.entity.agent.ActiveEntity.requestAction(ActiveEntity.java:119)
```

**Comment by kovax** [comment]
The root cause is in the castor mapping of the collection, the mapping for the DependencyMember does not have the ClassProps specified, therefore it is not stored
