### ISSUE TITLE
'member' property not injected for MemberRemoveScript

### ISSUE THREAD

**Issue by lorenzreyes** [cristal-ise/cristal-ise#201]
Related to issue https://github.com/TitusTech/hmws/issues/274

```
ERROR  : Error executing script Dependency_RemoveMember: IDL:org.cristalise.kernel/common/InvalidCollectionModification:1.0
EXCEPTION:org.cristalise.kernel.scripting.ScriptingEngineException: Parameters were not set: 
member
org.cristalise.kernel.common.InvalidCollectionModification: IDL:org.cristalise.kernel/common/InvalidCollectionModification:1.0
	at org.cristalise.kernel.common.InvalidCollectionModificationHelper.read(InvalidCollectionModificationHelper.java:70)
	at org.cristalise.kernel.entity._ItemStub.requestAction(_ItemStub.java:203)
	at org.cristalise.kernel.entity.proxy.AgentProxy.execute(AgentProxy.java:350)
	at org.cristalise.kernel.entity.proxy.AgentProxy$execute.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:141)
	at Script4.run(Script4.groovy:54)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
	at org.codehaus.groovy.jsr223.GroovyCompiledScript.eval(GroovyCompiledScript.java:72)
	at org.cristalise.kernel.scripting.Script.execute(Script.java:709)
	at org.cristalise.kernel.scripting.Script.evaluate(Script.java:652)
	at org.cristalise.kernel.entity.proxy.AgentProxy.callScript(AgentProxy.java:225)
	at org.cristalise.kernel.entity.proxy.AgentProxy.execute(AgentProxy.java:171)
	at org.cristalise.restapi.ItemUtils.executeJob(ItemUtils.java:675)
	at org.cristalise.restapi.ItemRoot.requestTransition(ItemRoot.java:370)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
	at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kovax** [comment]
All these changes to save one line of code in the script!?
