### ISSUE TITLE
Implement BulkExport predefined step

### ISSUE THREAD

**Issue by kovax** [cristal-ise/cristal-ise#236]
Implement BulkExport predefined step that can be triggered in the workflow of the Server item. This mechanism can be used to move data between servers, kind of replication.

**Comment by dlsdioquino** [comment]
Gene done with the implementation. Currently working on the JUnit test. Needs to modify the export for the attachment.

**Comment by genetorres** [comment]
Sample files that were created upon export 

![image](https://user-images.githubusercontent.com/41881351/60318581-38518c00-99a6-11e9-8c0b-a5959ee15e93.png)

**Comment by dlsdioquino** [comment]
Done for this. @kovax @taurus227 please review.

**Comment by dlsdioquino** [comment]
Working on the JOOQ functionality for this. The export works. However, import does not work as planned.

**Comment by dlsdioquino** [comment]
Working Export/Import using jooq. The implementation is mostly done, just creating a unit test for it.

**Comment by genetorres** [comment]
Test Result for LOCAL Grain DB

![image](https://user-images.githubusercontent.com/41881351/60568058-4d5f5e00-9d9e-11e9-8ec1-35f1232cd6a1.png)

![image](https://user-images.githubusercontent.com/41881351/60568071-58b28980-9d9e-11e9-9714-693c6a73b9bf.png)

![image](https://user-images.githubusercontent.com/41881351/60568078-5cdea700-9d9e-11e9-8b8e-d5cd8b5956c6.png)

**Comment by genetorres** [comment]
Test Result for HMWS (exporting OUTCOME table)

![image](https://user-images.githubusercontent.com/41881351/60568345-29e8e300-9d9f-11e9-9498-2134b16a9d0a.png)

**Comment by genetorres** [comment]
![image](https://user-images.githubusercontent.com/41881351/60572862-0f1b6c00-9da9-11e9-9582-6eed34c797fb.png)

**Comment by dlsdioquino** [comment]
Fixed the heap space issue when using jooq's `fetch().formatCSV()` when exporting big data by using `fetchLazy()` and `formatCSV(Writer writer)`  i.e. `context.selectFrom(EXPORT_TABLE).fetchLazy().formatCSV(writer);` to directly write the record to a writer / or it can be stream

**Comment by genetorres** [comment]
Test Result for exporting HMWS data

![image](https://user-images.githubusercontent.com/41881351/60645119-75b48e80-9e6a-11e9-8b73-0b8c32b6ac87.png)


hmws=# SELECT COUNT(*) FROM "OUTCOME";
 count
--------
 544926
(1 row)

hmws=# SELECT COUNT(*) FROM "ITEM";
 count
-------
 14469
(1 row)

hmws=# SELECT COUNT(*) FROM "ITEM_PROPERTY";
 count
-------
 73238
(1 row)

hmws=# SELECT COUNT(*) FROM "VIEWPOINT";
 count
-------
 89346
(1 row)
                         ^
hmws=# SELECT COUNT(*) FROM "ATTACHMENT";
 count
-------
     1
(1 row)


hmws=# SELECT COUNT(*) FROM "LIFECYCLE";
 count
-------
 14462
(1 row)

hmws=# SELECT COUNT(*) FROM "COLLECTION";
 count
-------
 19481
(1 row)

**Comment by genetorres** [comment]
Test Result for uploading all data from the exported csvfiles

![image](https://user-images.githubusercontent.com/41881351/60692553-1bb6d600-9f09-11e9-9346-2fd83e0460b8.png)

**Comment by genetorres** [comment]
Unable to login after importing same data for ITEM table

**Comment by lynetterussel331** [comment]
Trying the bulk insert function.

**Comment by genetorres** [comment]
Error when using bulk() wiith onDuplicateKeyUpdate()
`org.jooq.exception.LoaderConfigurationException: Cannot apply bulk loading with onDuplicateKey flags. Turn off either flag.
	at org.jooq.impl.LoaderImpl.checkFlags(LoaderImpl.java:648)
	at org.jooq.impl.LoaderImpl.execute(LoaderImpl.java:627)
	at org.jooq.impl.LoaderImpl.execute(LoaderImpl.java:99)
	at org.cristalise.storage.jooqdb.JooqDataImport.importItem(JooqDataImport.java:300)
	at com.titustech.hmws.test.workflow.BulkImportTest.importItem(BulkImportTest.groovy:204)
	at com.titustech.hmws.test.workflow.BulkImportTest.testItem(BulkImportTest.groovy:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
`

**Comment by genetorres** [comment]
Error fixed when onDuplicateKeyError() is used upon import

![image](https://user-images.githubusercontent.com/41881351/60853718-e9bab200-a22f-11e9-845e-e65ee372bd0b.png)

**Comment by genetorres** [comment]
TO DO : 
- [ ]  Document database structure for cristal-ise object and provide a flow for multi-site syncing option (fetching of cristal data on specific timestamp)

**Comment by genetorres** [comment]
[Item Data Structure.pdf](https://github.com/cristal-ise/cristal-ise/files/3371578/Item.Data.Structure.pdf)

**Comment by genetorres** [comment]
[Item Data Structure.pdf](https://github.com/cristal-ise/cristal-ise/files/3371585/Item.Data.Structure.pdf)

**Comment by dlsdioquino** [comment]
@taurus227 @kovax to review the document.

**Comment by dlsdioquino** [comment]
Starting on the SQL script by fetching the tables that we need to export using the event timestamp.

**Comment by kovax** [comment]
Reviewed,

**Comment by dlsdioquino** [comment]
Done implementing the export by timestamp. Doing a test right now, the test will be cover two databases from a database dump with different dates.

**Comment by genetorres** [comment]
Test Result: Created two data sets using HMWS prod_daily dump (07/07 and 07/10).

Event Count in HMWS 07/10 data set from last event recorded from (07/07)

![image](https://user-images.githubusercontent.com/41881351/61095181-ff74e500-a484-11e9-942e-05894e2f4dcd.png)

Export Test Result :

![image](https://user-images.githubusercontent.com/41881351/61095209-1b788680-a485-11e9-9967-d8885c083277.png)


Import Test Result:

![image](https://user-images.githubusercontent.com/41881351/61095247-3d720900-a485-11e9-9203-f08c82da4e3f.png)

Table Snapshot for HMWS 07/07

![image](https://user-images.githubusercontent.com/41881351/61095267-58447d80-a485-11e9-9994-17ac8ee61bad.png)

**Comment by dlsdioquino** [comment]
@kovax and @taurus227 please review.
