### ISSUE TITLE
Deadlock was detected while running test in-memory mode

### ISSUE THREAD

**Issue by kovax** [cristal-ise/cristal-ise#353]
While running all the tests of `org.cristalise.kernel.test.lifecycle.instance` a deadlock was detected. This is a special case, these tests use in-memory server, meaning the test code as client is running in the same process with the server. 

```java
Java stack information for the threads listed above:
===================================================
"Bootstrapper":
        at org.cristalise.kernel.entity.proxy.ItemProxy.subscribe(ItemProxy.java:1361)
        - waiting to lock <0x000000078ccd3e68> (a org.cristalise.kernel.entity.proxy.ItemProxy)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.<init>(DescriptionObjectCache.java:228)
        at org.cristalise.kernel.utils.DescriptionObjectCache.get(DescriptionObjectCache.java:166)
        - locked <0x000000068399c4f0> (a org.cristalise.kernel.utils.SoftCache)
        at org.cristalise.kernel.utils.LocalObjectLoader.getActDef(LocalObjectLoader.java:162)
        at org.cristalise.kernel.lifecycle.ActivitySlotDef.getTheActivityDef(ActivitySlotDef.java:102)
        at org.cristalise.kernel.lifecycle.CompositeActivityDef.findRefActDefs(CompositeActivityDef.java:309)
        at org.cristalise.kernel.lifecycle.CompositeActivityDef.setChildrenGraphModel(CompositeActivityDef.java:349)
        at sun.reflect.GeneratedMethodAccessor175.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.exolab.castor.mapping.loader.FieldHandlerImpl.setValue(FieldHandlerImpl.java:483)
        at org.exolab.castor.xml.EndElementProcessor.compute(EndElementProcessor.java:521)
        at org.exolab.castor.xml.UnmarshalHandler.endElement(UnmarshalHandler.java:473)
        at org.exolab.castor.xml.UnmarshalHandler.endElement(UnmarshalHandler.java:521)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.exolab.castor.xml.Unmarshaller.unmarshal(Unmarshaller.java:694)
        at org.exolab.castor.xml.Unmarshaller.unmarshal(Unmarshaller.java:589)
        at org.cristalise.kernel.utils.CastorXMLUtility.unmarshall(CastorXMLUtility.java:172)
        at org.cristalise.kernel.process.resource.DefaultResourceImportHandler.getCollections(DefaultResourceImportHandler.java:117)
        at org.cristalise.kernel.process.resource.DefaultResourceImportHandler.getCollections(DefaultResourceImportHandler.java:103)
        at org.cristalise.kernel.process.resource.DefaultResourceImportHandler.verifyResource(DefaultResourceImportHandler.java:234)
        at org.cristalise.kernel.process.resource.DefaultResourceImportHandler.importResource(DefaultResourceImportHandler.java:175)
        at org.cristalise.kernel.process.module.ModuleActivity.create(ModuleActivity.java:87)
        at org.cristalise.kernel.process.module.Module.importResources(Module.java:221)
        at org.cristalise.kernel.process.module.Module.importAll(Module.java:149)
        at org.cristalise.kernel.process.module.ModuleManager.registerModules(ModuleManager.java:251)
        at org.cristalise.kernel.process.Bootstrap$1.run(Bootstrap.java:120)
        at java.lang.Thread.run(Unknown Source)
"Proxy Client Connection Listener to localhost:1499":
        at org.cristalise.kernel.utils.DescriptionObjectCache.removeObject(DescriptionObjectCache.java:210)
        - waiting to lock <0x000000068399c4f0> (a org.cristalise.kernel.utils.SoftCache)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.add(DescriptionObjectCache.java:239)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.add(DescriptionObjectCache.java:1)
        at org.cristalise.kernel.entity.proxy.MemberSubscription.update(MemberSubscription.java:127)
        at org.cristalise.kernel.entity.proxy.ItemProxy.notify(ItemProxy.java:1407)
        - locked <0x000000078ccd3e68> (a org.cristalise.kernel.entity.proxy.ItemProxy)
        at org.cristalise.kernel.entity.proxy.ProxyManager.processMessage(ProxyManager.java:144)
        at org.cristalise.kernel.entity.proxy.ProxyServerConnection.run(ProxyServerConnection.java:78)

Found 1 deadlock.
```

**Comment by kovax** [comment]
It was detected while working on #344

**Comment by kovax** [comment]
Another deadlock was found during application testing using release 5.2.2:

```
"grizzly-http-server-31":
        at org.cristalise.kernel.utils.DescriptionObjectCache.get(DescriptionObjectCache.java:150)
        - waiting to lock <0x00000006c58b0520> (a org.cristalise.kernel.utils.SoftCache)
        at org.cristalise.kernel.utils.LocalObjectLoader.getScript(LocalObjectLoader.java:71)
        at org.cristalise.restapi.ScriptUtils.executeScript(ScriptUtils.java:101)
        at org.cristalise.restapi.ScriptAccess.handleScriptExecution(ScriptAccess.java:140)
        at org.cristalise.restapi.ScriptAccess.getScriptResultPost(ScriptAccess.java:126)

"grizzly-http-server-2":
        at org.cristalise.kernel.entity.proxy.ItemProxy.subscribe(ItemProxy.java:1362)
        - waiting to lock <0x00000006e1d00178> (a org.cristalise.kernel.entity.proxy.ItemProxy)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.<init>(DescriptionObjectCache.java:228)
        at org.cristalise.kernel.utils.DescriptionObjectCache.get(DescriptionObjectCache.java:166)
        - locked <0x00000006c58b0520> (a org.cristalise.kernel.utils.SoftCache)
        at org.cristalise.kernel.utils.LocalObjectLoader.getScript(LocalObjectLoader.java:71)
        at org.cristalise.restapi.ScriptUtils.executeScript(ScriptUtils.java:101)
        at org.cristalise.restapi.ItemRoot.getScriptResultPost(ItemRoot.java:234)

"Proxy Client Connection Listener to localhost:1555":
        at org.cristalise.kernel.utils.DescriptionObjectCache.removeObject(DescriptionObjectCache.java:210)
        - waiting to lock <0x00000006c58b0520> (a org.cristalise.kernel.utils.SoftCache)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.add(DescriptionObjectCache.java:239)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.add(DescriptionObjectCache.java:217)
        at org.cristalise.kernel.entity.proxy.MemberSubscription.update(MemberSubscription.java:127)
        at org.cristalise.kernel.entity.proxy.ItemProxy.notify(ItemProxy.java:1407)
        - locked <0x00000006e1d00178> (a org.cristalise.kernel.entity.proxy.ItemProxy)
        at org.cristalise.kernel.entity.proxy.ProxyManager.processMessage(ProxyManager.java:144)
        at org.cristalise.kernel.entity.proxy.ProxyServerConnection.run(ProxyServerConnection.java:78)
```
