### ISSUE TITLE
The JobList of the UserCode cannot be updated

### ISSUE THREAD

**Issue by kovax** [cristal-ise/cristal-ise#427]
This exception is thrown when the kernel tries to store the Job for the Agent (e.g. UserCode) with persistent JobList:

```
12:28:24.483 [Agent job pusher for /entity/f0f7b48e-87a3-4807-8699-b0b0f42e0532:workflow/domain/SetAggregated-2020-09-07_12-27-49_381 to role /role/UserCode] ERROR o.c.kernel.persistency.RemoteMap - 
org.cristalise.kernel.common.PersistencyException: IDL:org.cristalise.kernel/common/PersistencyException:1.0  locker cannot be null when autoCommit is false
	at org.cristalise.storage.jooqdb.JooqClusterStorage.put(JooqClusterStorage.java:485)
	at org.cristalise.storage.jooqdb.JooqClusterStorage.put(JooqClusterStorage.java:479)
	at org.cristalise.kernel.persistency.ClusterStorageManager.put(ClusterStorageManager.java:339)
	at org.cristalise.kernel.persistency.ClusterStorageManager.put(ClusterStorageManager.java:324)
	at org.cristalise.kernel.persistency.TransactionManager.put(TransactionManager.java:195)
	at org.cristalise.kernel.persistency.RemoteMap.put(RemoteMap.java:286)
	at org.cristalise.kernel.entity.agent.JobList.addJob(JobList.java:50)
	at org.cristalise.kernel.entity.agent.AgentImplementation.refreshJobList(AgentImplementation.java:83)
	at org.cristalise.kernel.entity.agent.ActiveEntity.refreshJobList(ActiveEntity.java:76)
```

**Comment by kovax** [comment]
RemoteMap be initialized with a transaction key (locker), and the Joblist (subclass of RemoteMap) is initialized inside of the AgentImplementation. The locker can be different for each transaction, therefore storing the locker in the JobList will never find the required transaction. 

The solution is extending each method of RemoteMap/JobList/History with the locker ...
