### ISSUE TITLE
Deadlock caused by editing a Script

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#447]
If a user is editing a Script while another user is trying to execute it, it can cause a deadlock.

Thread dump:
```
Found one Java-level deadlock:
=============================
"grizzly-http-server-31":
  waiting to lock monitor 0x00007f0d7c00bad8 (object 0x00000006c58b0520, a org.cristalise.kernel.utils.SoftCache),
  which is held by "grizzly-http-server-2"
"grizzly-http-server-2":
  waiting to lock monitor 0x00007f0e89ebb8b8 (object 0x00000006e1d00178, a org.cristalise.kernel.entity.proxy.ItemProxy),
  which is held by "Proxy Client Connection Listener to localhost:1555"
"Proxy Client Connection Listener to localhost:1555":
  waiting to lock monitor 0x00007f0d7c00bad8 (object 0x00000006c58b0520, a org.cristalise.kernel.utils.SoftCache),
  which is held by "grizzly-http-server-2"

Java stack information for the threads listed above:
===================================================
"grizzly-http-server-31":
        at org.cristalise.kernel.utils.DescriptionObjectCache.get(DescriptionObjectCache.java:150)
        - waiting to lock <0x00000006c58b0520> (a org.cristalise.kernel.utils.SoftCache)
        at org.cristalise.kernel.utils.LocalObjectLoader.getScript(LocalObjectLoader.java:71)
        at org.cristalise.restapi.ScriptUtils.executeScript(ScriptUtils.java:101)
        at org.cristalise.restapi.ScriptAccess.handleScriptExecution(ScriptAccess.java:140)
        at org.cristalise.restapi.ScriptAccess.getScriptResultPost(ScriptAccess.java:126)
        at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
"grizzly-http-server-2":
        at org.cristalise.kernel.entity.proxy.ItemProxy.subscribe(ItemProxy.java:1362)
        - waiting to lock <0x00000006e1d00178> (a org.cristalise.kernel.entity.proxy.ItemProxy)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.<init>(DescriptionObjectCache.java:228)
        at org.cristalise.kernel.utils.DescriptionObjectCache.get(DescriptionObjectCache.java:166)
        - locked <0x00000006c58b0520> (a org.cristalise.kernel.utils.SoftCache)
        at org.cristalise.kernel.utils.LocalObjectLoader.getScript(LocalObjectLoader.java:71)
        at org.cristalise.restapi.ScriptUtils.executeScript(ScriptUtils.java:101)
        at org.cristalise.restapi.ItemRoot.getScriptResultPost(ItemRoot.java:234)
        at sun.reflect.GeneratedMethodAccessor382.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
"Proxy Client Connection Listener to localhost:1555":
        at org.cristalise.kernel.utils.DescriptionObjectCache.removeObject(DescriptionObjectCache.java:210)
        - waiting to lock <0x00000006c58b0520> (a org.cristalise.kernel.utils.SoftCache)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.add(DescriptionObjectCache.java:239)
        at org.cristalise.kernel.utils.DescriptionObjectCache$CacheEntry.add(DescriptionObjectCache.java:217)
        at org.cristalise.kernel.entity.proxy.MemberSubscription.update(MemberSubscription.java:127)
        at org.cristalise.kernel.entity.proxy.ItemProxy.notify(ItemProxy.java:1407)
        - locked <0x00000006e1d00178> (a org.cristalise.kernel.entity.proxy.ItemProxy)
        at org.cristalise.kernel.entity.proxy.ProxyManager.processMessage(ProxyManager.java:144)
        at org.cristalise.kernel.entity.proxy.ProxyServerConnection.run(ProxyServerConnection.java:78)

Found 1 deadlock.
```

**Comment by taurus227** [comment]
Current (deadlock) functionality:
1. [grizzly-http-server-2] DescriptionObjectCache.get locks the cache (a SoftCache object)
2. [grizzly-http-server-2] DescriptionObjectCache.get checks if the Script object is in the cache
3. [Proxy Client] Somebody changed the Script object in the meantime, so the Proxy Client gets a notification and tries to refresh it. Therefore it locks the ItemProxy first, then tries to add it to the cache, so it attempts to lock the cache (but it's already locked)
4. [grizzly-http-server-2] If the Script object is not in the cache, it attempts to create the CacheEntry, therefore attempts to lock the ItemProxy (but it's already locked)

New implementation to avoid deadlock - change the order of locks:
1. [grizzly-http-server-2] DescriptionObjectCache.get locks the cache (a SoftCache object)
2. [grizzly-http-server-2] DescriptionObjectCache.get checks if the Script object is in the cache
3. [grizzly-http-server-2] Gives up it's lock on the cache
3. [grizzly-http-server-2] If the Script object is not in the cache, it attempts to create the CacheEntry, therefore locks the ItemProxy
4. [grizzly-http-server-2] Locks the cache again (crucially, after the ItemProxy lock)
5. [grizzly-http-server-2] Adds Script object to the cache
