### ISSUE TITLE
Bootstrap performance

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#449]
Bootstrap is slow on test environment, takes about 20 minutes. In production only takes 2 minutes.
Whenever we deploy a new version of the system, we have to wait 20 minutes for it to be usable.

## Stats
This is on a test server:
The Bootstrap was started at 23:47, I reset the stats counter only at 23:01.
Bootstrap finished at 23:10, so the below stats are for the remaining 9 minutes of the bootstrap.
As can be seen below, most of the time (537 s) was spent in the query that looks up an item by Type and Name.

```
  queryid   |                    short_query                     | total_time | calls |  mean  |  avg   | stddev_time | percentage_cpu
------------+----------------------------------------------------+------------+-------+--------+--------+-------------+----------------
 3376642699 | select "PATH", "TARGET" from "DOMAIN_PATH" left ou |  537903.12 |  2246 | 239.49 | 239.49 |      162.65 |          99.81
```

This is the offending query:
```sql
SELECT "PATH",
       "TARGET"
FROM "DOMAIN_PATH"
LEFT OUTER JOIN "ITEM_PROPERTY" AS "Name" ON "TARGET" = "Name"."UUID"
LEFT OUTER JOIN "ITEM_PROPERTY" AS "Type" ON "TARGET" = "Type"."UUID"
WHERE ("Name"."NAME" = $1
       AND upper("Name"."VALUE") like upper($2)
       AND "Type"."NAME" = $3
       AND upper("Type"."VALUE") like upper($4)
       AND "PATH" like $5)
ORDER BY "PATH"
```

The query is executed by `JooqLookupManager.search()` defined in
https://github.com/cristal-ise/cristal-ise/blob/e1006fe3e771c9b6c3d33a60c79246b65dbbf70f/jooqdb/src/main/java/org/cristalise/storage/jooqdb/lookup/JooqLookupManager.java#L472

This is called by `DescriptionObjectCache.findItem(String name)` from
https://github.com/cristal-ise/cristal-ise/blob/a83f8e6a16feaf7066963e7fde93c0a4c4e12d4f/kernel/src/main/java/org/cristalise/kernel/utils/DescriptionObjectCache.java#L136

## Proposed Solution
Add a "search" function to LookupManager dedicated to be used by the bootstrap. 
We could call it `findByTypeAndName()`.
This could contain a greatly simplified query, either by constructing the path and only querying the DOMAIN_PATH table:
```sql
SELECT "PATH",
       "TARGET" 
  FROM "DOMAIN_PATH" 
 WHERE "PATH" = '/domain/desc/Script/hmws/WorkOrder_Update';
```
or a simplified version of the currently generated query (no need for LEFT OUTER, ORDER BY, UPPER, LIKE):
```sql
SELECT "PATH",
       "TARGET"
  FROM "DOMAIN_PATH" dp
  JOIN "ITEM_PROPERTY" AS "Name" ON dp."TARGET" = "Name"."UUID" AND "Name"."NAME" = 'Name'
  JOIN "ITEM_PROPERTY" AS "Type" ON dp."TARGET" = "Type"."UUID" AND "Type"."NAME" = 'Type'
 WHERE "Name"."VALUE" = 'WorkOrder_Update'
   AND "Type"."VALUE" = 'Script'
```

**Comment by kovax** [comment]
@taurus227 thanks for the issue.

The Bootstrap only depends on the ClusterStorage API in order to keep it independent from backend implementation. Also the LocalObjectLoader implementation is also based on the DescriptionObjectCache API, and the LocalObjectLoader can be used anytime during the application lifecycle (i.e. not specific to Bootstrap).

I agree, that it is important to improve the performance of the Bootstrap, but I do not think that the suggested change is a good approach. If the bootstrap time is acceptable for the production system, then use similar setup for the functional test environments, because it will be much quicker and cheaper compared to the development cost of this new feature/optimization. If you use virtualization, check if the generated VM has all optimization setting to achieve best performance, and make sure that the actual hardware is good to host VMs.

I also would wait for the completion of #347, because it could change the scope of this issue.

**Comment by taurus227** [comment]
It's not realistic to have the same setup for test environments as for production. We actually cloned the production VM, so it's exactly the same OS, database and so on. But while in production that's the only VM running on that machine, we have a number of VMs that we use for testing. It would cost a lot of money to buy identical hardware for each test VM. And bootstrap would still take a lot of time in the developer's local environment.

**Comment by kovax** [comment]
Before we start to do any brainstorming on this topic, you need to make sure, that your VM setup is properly done fully optimized to run efficiently many VMs in parallel.

- Make sure the using one VM has the same performance of the production setup
- Launch VMs one-by-one and see the performance of bootstrap. If you have correctly VM setup, the time of bootstrap should increase linearly.

I guess the system will be saturated quickly. If the saturation happens when you are running only 2-3 VMs, I think something is fundamentally wrong with your setup. Perhaps you need a much better SSD drive, or the CPU cores are not enough.

**Comment by taurus227** [comment]
I just switched on query timing in psql with
\timing on
and ran the 3 different queries manually 3 times each.

Did it on our PROD VM, Prod_Clone VM and the DevBox VM that is running on my laptop.

![image](https://user-images.githubusercontent.com/5892152/100639942-c89cb900-3370-11eb-99d2-b8569b9d6af6.png)
[Bootstrap Query Performance.xlsx](https://github.com/cristal-ise/cristal-ise/files/5617403/Bootstrap.Query.Performance.xlsx)

[Bootstrap Query Performance Local VM.txt](https://github.com/cristal-ise/cristal-ise/files/5617408/Bootstrap.Query.Performance.Local.VM.txt)
[Bootstrap Query Performance PROD VM.txt](https://github.com/cristal-ise/cristal-ise/files/5617409/Bootstrap.Query.Performance.PROD.VM.txt)
[Bootstrap Query Performance Prod_Clone VM.txt](https://github.com/cristal-ise/cristal-ise/files/5617410/Bootstrap.Query.Performance.Prod_Clone.VM.txt)

**Comment by taurus227** [comment]
Hacked the query into Cristal on the 5.3.2 branch.
Also added some logging for paths that it didn't find.

It runs the query 3300 times for paths that cannot be found!
Here are the paths preceded by the number of lookup attempts during bootstrap:
```
   1642 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/Script
    694 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/ElementaryActivityDef
    232 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/CompositeActivityDef
    173 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/StateMachine/hmws/CompositeActivity
    163 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/PropertyDescription
    132 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/Factory_DBInsert
     93 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/StateMachine/hmws/Default
     61 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/StateMachine/hmws/PredefinedStep
     52 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/ItemInitialization
     20 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/StateMachine
     18 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/Module_DBInsert
     12 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/Module
      7 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/ModuleChanges
      7 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/CreateNewLocalObjectDef
      6 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ManageModule
      5 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/CreateItem
      4 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/Planner_DBInsert
      3 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/SetInstanceWorkflow
      3 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/EditPropertyDescription
      3 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/EditDefinition
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/Type_DBInsert
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/Query
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/NewDevObjectDef
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/StateMachineFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ScriptFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/SchemaFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/QueryFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ModuleFactory
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ItemDescriptionFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ElementaryActivityFactory
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/EditModuleConfiguration
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/EditModuleAgents
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/DefineNewCollection
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/CreateAgent
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/CompositeActivityFactory
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/AgentFactoryWf
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/SetWorkflow
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/LocalObjectDefCreator
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/InstantiateItem
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/InstantiateAgent
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/hmws/CollDescCreator
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/SystemProperties
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/NewCollection
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/NewAgent
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/hmws/ChooseWorkflow
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ServerItemWorkflow
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ReadOnlyItemDescriptionWf
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/NoWorkflow
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ItemDescriptionWf
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/ExportModule
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/CreateNewRole
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/CreateNewItem
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/hmws/CreateNewAgent
```

**Comment by taurus227** [comment]
These lookups are called from this stack:
```
        at org.cristalise.storage.jooqdb.lookup.JooqLookupManager.getItemPath(JooqLookupManager.java:257)
        at org.cristalise.kernel.utils.DescriptionObjectCache.findItem(DescriptionObjectCache.java:133)
        at org.cristalise.kernel.utils.DescriptionObjectCache.get(DescriptionObjectCache.java:162)
        at org.cristalise.kernel.utils.LocalObjectLoader.getActDef(LocalObjectLoader.java:149)
        at org.cristalise.kernel.process.Bootstrap.initServerItemWf(Bootstrap.java:343)
        at org.cristalise.kernel.process.Bootstrap.createServerItem(Bootstrap.java:330)
        at org.cristalise.kernel.process.Bootstrap.init(Bootstrap.java:89)
        at org.cristalise.kernel.process.Bootstrap.run(Bootstrap.java:106)
        at org.cristalise.kernel.process.Gateway.runBoostrap(Gateway.java:549)
        at org.cristalise.kernel.process.StandardServer.standardInitialisation(StandardServer.java:115)
        at org.cristalise.kernel.process.StandardServer.standardInitialisation(StandardServer.java:128)
        at org.cristalise.kernel.process.StandardServer.main(StandardServer.java:139)
```

**Comment by taurus227** [comment]
See log for the stack trace of each of those.
[cristal.log.txt](https://github.com/cristal-ise/cristal-ise/files/5618314/cristal.log.txt)

**Comment by kovax** [comment]
`/domain/desc/Schema/hmws/Script` does not exists for sure, because it is a kernel defined resource. it is available as `/domain/desc/Schema/kernel/Script`, so replace hmws with kernel, and it will work. 

Unfortunately you changes cff282ba5af7f1cf3216bc4417ff455a56915ff9 will not work. I can help to fix it.

**Comment by taurus227** [comment]
As a test, I added a first fallback: if it doesn't find `/domain/desc/$type/`**`hmws`**`/$name`, it runs another query to look for `/domain/desc/$type/`**`kernel`**`/$name` and only falls back to the original query if it doesn't find the item from either of those queries.

Even though this means 2 SQL select statements instead of one, this made the bootstrap run in 2 minutes instead of 20!

There are still some stuff that it doesn't find:
```
    132 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/Factory_DBInsert
     18 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/Module_DBInsert
      7 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/CreateNewLocalObjectDef
      5 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/CreateItem
      4 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/Planner_DBInsert
      3 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/SetInstanceWorkflow
      3 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/EditPropertyDescription
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/Type_DBInsert
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/kernel/NewDevObjectDef
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/StateMachineFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/ScriptFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/SchemaFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/QueryFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/ModuleFactory
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/ItemDescriptionFactoryWf
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/ElementaryActivityFactory
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/DefineNewCollection
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/CreateAgent
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/CompositeActivityFactory
      2 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/AgentFactoryWf
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/SetWorkflow
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/LocalObjectDefCreator
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/InstantiateItem
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/InstantiateAgent
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Script/kernel/CollDescCreator
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/kernel/NewCollection
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/kernel/NewAgent
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/Schema/kernel/ChooseWorkflow
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/ReadOnlyItemDescriptionWf
      1 JooqLookupManager - getItemPath: Could not find DomainPath /domain/desc/ActivityDesc/kernel/ItemDescriptionWf
```
