### ISSUE TITLE
Many log entries saying Script Factory_Aggregate not found

### ISSUE THREAD

**Issue by taurus227** [cristal-ise/cristal-ise#510]
Cristal 5.5.0 produces such logs every time we open a New Item form:
```
09:28:27.251 r15000184 [grizzly-http-server-7] ERROR o.c.k.utils.DescriptionObjectCache - get() -
org.cristalise.kernel.common.ObjectNotFoundException: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0  Resource Script Factory_Aggregate not found in bootstrap resources
        at org.cristalise.kernel.utils.DescriptionObjectCache.loadObjectFromBootstrap(DescriptionObjectCache.java:113)
        at org.cristalise.kernel.utils.DescriptionObjectCache.get(DescriptionObjectCache.java:233)
        at org.cristalise.kernel.utils.LocalObjectLoader.getScript(LocalObjectLoader.java:78)
        at org.cristalise.kernel.entity.proxy.ItemProxy.getAggregateScript(ItemProxy.java:1394)
        at org.cristalise.kernel.entity.proxy.ItemProxy.getAggregateScript(ItemProxy.java:1358)
        at org.cristalise.restapi.ItemRoot.getAggregateScript(ItemRoot.java:186)
        at org.cristalise.restapi.ItemRoot.getAggregateScript(ItemRoot.java:173)
        at org.cristalise.restapi.ItemRoot.getItemSummary(ItemRoot.java:315)
        at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
09:28:27.270 r15000203 [grizzly-http-server-5] WARN  o.c.kernel.entity.proxy.ItemProxy - getAggregateScript() - Version for Script 'Factory_Aggregate' was null, using version 0 as default
09:28:27.299 r15000232 [grizzly-http-server-5] ERROR o.c.k.utils.DescriptionObjectCache - get() -
org.cristalise.kernel.common.ObjectNotFoundException: IDL:org.cristalise.kernel/common/ObjectNotFoundException:1.0  Resource Script Factory_Aggregate not found in bootstrap resources
        at org.cristalise.kernel.utils.DescriptionObjectCache.loadObjectFromBootstrap(DescriptionObjectCache.java:113)
        at org.cristalise.kernel.utils.DescriptionObjectCache.get(DescriptionObjectCache.java:233)
        at org.cristalise.kernel.utils.LocalObjectLoader.getScript(LocalObjectLoader.java:78)
        at org.cristalise.kernel.entity.proxy.ItemProxy.getAggregateScript(ItemProxy.java:1394)
        at org.cristalise.kernel.entity.proxy.ItemProxy.getAggregateScript(ItemProxy.java:1358)
        at org.cristalise.restapi.ItemRoot.getAggregateScript(ItemRoot.java:186)
        at org.cristalise.restapi.ItemRoot.getAggregateScript(ItemRoot.java:173)
        at org.cristalise.restapi.ItemRoot.getItemSummary(ItemRoot.java:315)
        at sun.reflect.GeneratedMethodAccessor159.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:377)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.lang.Thread.run(Thread.java:748)
```

It seems that the change is in logging. It seems that when an object wasn't able to be loaded from bootstrap it wasn't being logged until v5.4.0. And adding [that improved logging during bootstrap](https://github.com/cristal-ise/cristal-ise/commit/add87f63e72f116a356662c8d1a3c4213f2eb36e#diff-8f542ad7308bebebe111b5252fea14138217fc3fe1cdcc555bb25683b70ae5eaR235-R237) had the side-effect of logging when a script is not found. I think we need to add some kind of configuration so that the `ItemRoot.getItemSummary` doesn't try to load an `_Aggregate` script for items like `Factory`.

**Comment by kovax** [comment]
`ItemRoot.getItemSummary()` does not need to retrieve the aggreagateScript to check if the item has MasterOutcome or not. So 

- either swallow the exception in a try-catch block 
- or use `ItemProxy.checkObject()` instead of `getAggregateScript()`
